# Vintage Diagnostics (pre-Phase 5 correction)

Measures three parameters currently assumed rather than measured:

1. **Is the 2016 OOT set trustworthy?** — observed vs lower-bound default rate per vintage.
2. **Where should the train window start?** — first year each bureau feature is actually collected.
3. **What outcome horizon H?** — month-on-book by which ~90% of a vintage's defaults have resolved.

Runs on the RAW ingested frame. `build_target()` must NOT run first: it drops exactly the
censored rows this notebook needs to count.

In [1]:
from pathlib import Path

import polars as pl

from credit_risk.data.ingestion import load_raw_accepted_loans
from credit_risk.data.diagnostics import (
    censoring_by_vintage,
    default_hazard_by_mob,
    feature_availability,
    first_reliable_year,
    prepayment_risk_link,
)

pl.Config.set_tbl_rows(60)
pl.Config.set_tbl_cols(40)

DATA_PATH = Path("../data/raw/accepted_2007_to_2018Q4.csv")
raw = load_raw_accepted_loans(DATA_PATH)
print(raw.shape)

(2260668, 151)

## 1. Censoring bias per vintage

`dr_observed` is what `build_target()` currently reports (defaults / matured).
`dr_lower_bnd` is defaults / issued — the true rate if no censored loan ever defaults.
The true vintage rate lies between them; `bias_gap` is the size of the distortion.

**Decision rule:** any vintage whose `bias_gap` exceeds ~2pp cannot be used as an
evaluation set under the current target definition.

In [2]:
censoring = censoring_by_vintage(raw)
censoring

shape: (12, 8)
┌────────────┬──────────┬───────────┬───────────┬─────────────┬────────────┬────────────┬──────────┐
│ issue_year ┆ n_issued ┆ n_matured ┆ n_default ┆ pct_censore ┆ dr_observe ┆ dr_lower_b ┆ bias_gap │
│ ---        ┆ ---      ┆ ---       ┆ ---       ┆ d           ┆ d          ┆ nd         ┆ ---      │
│ i32        ┆ u32      ┆ u32       ┆ u32       ┆ ---         ┆ ---        ┆ ---        ┆ f64      │
│            ┆          ┆           ┆           ┆ f64         ┆ f64        ┆ f64        ┆          │
╞════════════╪══════════╪═══════════╪═══════════╪═════════════╪════════════╪════════════╪══════════╡
│ 2007       ┆ 603      ┆ 603       ┆ 158       ┆ 0.0         ┆ 0.262023   ┆ 0.262023   ┆ 0.0      │
│ 2008       ┆ 2393     ┆ 2393      ┆ 496       ┆ 0.0         ┆ 0.207271   ┆ 0.207271   ┆ 0.0      │
│ 2009       ┆ 5281     ┆ 5281      ┆ 723       ┆ 0.0         ┆ 0.136906   ┆ 0.136906   ┆ 0.0      │
│ 2010       ┆ 12537    ┆ 12537     ┆ 1757      ┆ 0.0         ┆ 0.140145   ┆ 0.140145   ┆ 0.0      │
│ 2011       ┆ 21721    ┆ 21721     ┆ 3297      ┆ 0.0         ┆ 0.151789   ┆ 0.151789   ┆ 0.0      │
│ 2012       ┆ 53367    ┆ 53367     ┆ 8644      ┆ 0.0         ┆ 0.161973   ┆ 0.161973   ┆ 0.0      │
│ 2013       ┆ 134814   ┆ 134804    ┆ 21024     ┆ 0.000074    ┆ 0.15596    ┆ 0.155948   ┆ 0.000012 │
│ 2014       ┆ 235629   ┆ 223103    ┆ 41162     ┆ 0.05316     ┆ 0.184498   ┆ 0.17469    ┆ 0.009808 │
│ 2015       ┆ 421095   ┆ 375546    ┆ 75804     ┆ 0.108168    ┆ 0.20185    ┆ 0.180016   ┆ 0.021834 │
│ 2016       ┆ 434407   ┆ 293105    ┆ 68252     ┆ 0.325276    ┆ 0.232859   ┆ 0.157115   ┆ 0.075743 │
│ 2017       ┆ 443579   ┆ 169321    ┆ 39169     ┆ 0.618284    ┆ 0.23133    ┆ 0.088302   ┆ 0.143028 │
│ 2018       ┆ 495242   ┆ 56318     ┆ 8874      ┆ 0.886282    ┆ 0.15757    ┆ 0.017919   ┆ 0.139651 │
└────────────┴──────────┴───────────┴───────────┴─────────────┴────────────┴────────────┴──────────┘

In [3]:
# Export for review alongside this notebook.
censoring.write_csv("../docs/vintage_censoring.csv")

## 2. Feature availability per vintage

LendingClub expanded bureau collection in stages. A feature whose null rate collapses
from ~1.0 to ~0.0 at some year is vintage dependent: its WOE `missing` bin encodes
calendar time, not credit risk, and that bin is never hit at serving time.

Half of `SCORECARD_FEATURES` is suspected to be in this group.

In [4]:
SUSPECT_FEATURES = [
    # kept in SCORECARD_FEATURES, suspected post-2012 bureau expansion
    "acc_open_past_24mths", "mort_acc", "mths_since_recent_bc", "avg_cur_bal",
    "bc_open_to_buy", "num_rev_tl_bal_gt_0", "mo_sin_rcnt_tl", "mths_since_recent_inq",
    # control group: expected available from 2007
    "fico_range_low", "dti", "annual_inc", "revol_util", "open_acc",
    # opposite direction: suspected to start only in 2016 (absent in train)
    "disbursement_method", "initial_list_status",
]

availability = feature_availability(raw, SUSPECT_FEATURES)
availability

shape: (12, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ iss ┆ n   ┆ acc ┆ mor ┆ mth ┆ avg ┆ bc_ ┆ num ┆ mo_ ┆ mth ┆ fic ┆ dti ┆ ann ┆ rev ┆ ope ┆ dis ┆ ini │
│ ue_ ┆ --- ┆ _op ┆ t_a ┆ s_s ┆ _cu ┆ ope ┆ _re ┆ sin ┆ s_s ┆ o_r ┆ --- ┆ ual ┆ ol_ ┆ n_a ┆ bur ┆ tia │
│ yea ┆ u32 ┆ en_ ┆ cc  ┆ inc ┆ r_b ┆ n_t ┆ v_t ┆ _rc ┆ inc ┆ ang ┆ f64 ┆ _in ┆ uti ┆ cc  ┆ sem ┆ l_l │
│ r   ┆     ┆ pas ┆ --- ┆ e_r ┆ al  ┆ o_b ┆ l_b ┆ nt_ ┆ e_r ┆ e_l ┆     ┆ c   ┆ l   ┆ --- ┆ ent ┆ ist │
│ --- ┆     ┆ t_2 ┆ f64 ┆ ece ┆ --- ┆ uy  ┆ al_ ┆ tl  ┆ ece ┆ ow  ┆     ┆ --- ┆ --- ┆ f64 ┆ _me ┆ _st │
│ i32 ┆     ┆ 4mt ┆     ┆ nt_ ┆ f64 ┆ --- ┆ gt_ ┆ --- ┆ nt_ ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆ tho ┆ atu │
│     ┆     ┆ hs  ┆     ┆ bc  ┆     ┆ f64 ┆ 0   ┆ f64 ┆ inq ┆ f64 ┆     ┆     ┆     ┆     ┆ d   ┆ s   │
│     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- │
│     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 200 ┆ 603 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 066 ┆ 530 ┆ 480 ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 33  ┆ 68  ┆ 93  ┆     ┆     │
│ 200 ┆ 239 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 8   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 050 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 15  ┆     ┆     ┆     │
│ 200 ┆ 528 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 9   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 030 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     │
│ 201 ┆ 125 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 0   ┆ 37  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 016 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 75  ┆     ┆     ┆     │
│ 201 ┆ 217 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 1   ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 004 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14  ┆     ┆     ┆     │
│ 201 ┆ 533 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.5 ┆ 0.1 ┆ 0.5 ┆ 0.5 ┆ 0.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 2   ┆ 67  ┆ 404 ┆ 404 ┆ 489 ┆ 198 ┆ 502 ┆ 198 ┆ 198 ┆ 489 ┆     ┆     ┆     ┆ 008 ┆     ┆     ┆     │
│     ┆     ┆ 43  ┆ 43  ┆ 31  ┆ 16  ┆ 61  ┆ 16  ┆ 16  ┆ 55  ┆     ┆     ┆     ┆ 81  ┆     ┆     ┆     │
│ 201 ┆ 134 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 3   ┆ 814 ┆     ┆     ┆ 065 ┆ 000 ┆ 074 ┆     ┆     ┆ 081 ┆     ┆     ┆     ┆ 005 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 28  ┆ 45  ┆ 62  ┆     ┆     ┆ 64  ┆     ┆     ┆     ┆ 79  ┆     ┆     ┆     │
│ 201 ┆ 235 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 4   ┆ 629 ┆     ┆     ┆ 095 ┆ 000 ┆ 103 ┆     ┆     ┆ 920 ┆     ┆     ┆     ┆ 005 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 32  ┆ 25  ┆ 76  ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     │
│ 201 ┆ 421 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 5   ┆ 095 ┆     ┆     ┆ 090 ┆     ┆ 094 ┆     ┆     ┆ 059 ┆     ┆ 000 ┆     ┆ 003 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 19  ┆     ┆ 11  ┆     ┆     ┆ 12  ┆     ┆ 05  ┆     ┆ 85  ┆     ┆     ┆     │
│ 201 ┆ 434 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 6   ┆ 407 ┆     ┆     ┆ 100 ┆     ┆ 106 ┆     ┆     ┆ 047 ┆     ┆ 001 ┆     ┆ 006 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 69  ┆     ┆ 7   ┆     ┆     ┆ 01  ┆     ┆ 45  ┆     ┆ 08  ┆     ┆     ┆     │
│ 201 ┆ 443 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 7   ┆ 579 ┆     ┆     ┆ 122 ┆ 000 ┆ 129 ┆     ┆     ┆ 171 ┆     ┆ 011 ┆     ┆ 010 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 48  ┆ 41  ┆ 49  ┆     ┆     ┆ 22  ┆     ┆ 59  ┆     ┆ 01  ┆     ┆     ┆     │
│ 201 ┆ 495 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ 8   ┆ 242 ┆     ┆     ┆ 125 ┆ 000 ┆ 133 ┆     ┆     ┆ 237 ┆     ┆ 022 ┆     ┆ 011 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ 15  ┆ 81  ┆ 03  ┆     ┆     ┆ 88  ┆     ┆ 86  ┆     ┆ 95  ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [5]:
first_reliable_year(availability, max_null_rate=0.05)

shape: (15, 2)
┌───────────────────────┬────────────┐
│ feature               ┆ first_year │
│ ---                   ┆ ---        │
│ str                   ┆ i32        │
╞═══════════════════════╪════════════╡
│ annual_inc            ┆ 2007       │
│ disbursement_method   ┆ 2007       │
│ dti                   ┆ 2007       │
│ fico_range_low        ┆ 2007       │
│ initial_list_status   ┆ 2007       │
│ open_acc              ┆ 2007       │
│ revol_util            ┆ 2008       │
│ acc_open_past_24mths  ┆ 2013       │
│ avg_cur_bal           ┆ 2013       │
│ bc_open_to_buy        ┆ 2013       │
│ mo_sin_rcnt_tl        ┆ 2013       │
│ mort_acc              ┆ 2013       │
│ mths_since_recent_bc  ┆ 2013       │
│ num_rev_tl_bal_gt_0   ┆ 2013       │
│ mths_since_recent_inq ┆ null       │
└───────────────────────┴────────────┘

In [6]:
availability.write_csv("../docs/vintage_feature_availability.csv")

## 3. Default timing — choosing the outcome horizon H

Run on fully matured vintages only (2012–2013). Charge-off date is not published by
LendingClub, so it is proxied as `last_pymnt_d + 5` months (LC charges off at ~121 days
delinquent).

**Two things to read here:**
- *Proxy validity:* `n_default` should peak around MOB 8–18 and decline. A flat or
  bimodal shape means the proxy is wrong and H cannot be set from it.
- *Horizon:* the MOB where `cum_share` reaches ~0.90, separately for 36 and 60 month terms.

In [7]:
hazard = default_hazard_by_mob(raw, vintages=[2012, 2013])

for term in sorted(hazard["term_months"].unique()):
    sub = hazard.filter(pl.col("term_months") == term)
    for q in (0.50, 0.75, 0.90, 0.95):
        mob = sub.filter(pl.col("cum_share") >= q)["mob"].min()
        print(f"term={term}m  {q:.0%} of defaults resolved by MOB {mob}")
    print()

term=36m  50% of defaults resolved by MOB 22
term=36m  75% of defaults resolved by MOB 29
term=36m  90% of defaults resolved by MOB 35
term=36m  95% of defaults resolved by MOB 37

term=60m  50% of defaults resolved by MOB 27
term=60m  75% of defaults resolved by MOB 39
term=60m  90% of defaults resolved by MOB 49
term=60m  95% of defaults resolved by MOB 55

In [8]:
hazard.filter(pl.col("term_months") == 36).head(40)

shape: (40, 4)
┌─────────────┬─────┬───────────┬───────────┐
│ term_months ┆ mob ┆ n_default ┆ cum_share │
│ ---         ┆ --- ┆ ---       ┆ ---       │
│ i32         ┆ i32 ┆ u32       ┆ f64       │
╞═════════════╪═════╪═══════════╪═══════════╡
│ 36          ┆ 6   ┆ 179       ┆ 0.009862  │
│ 36          ┆ 7   ┆ 297       ┆ 0.026226  │
│ 36          ┆ 8   ┆ 369       ┆ 0.046556  │
│ 36          ┆ 9   ┆ 447       ┆ 0.071185  │
│ 36          ┆ 10  ┆ 465       ┆ 0.096804  │
│ 36          ┆ 11  ┆ 544       ┆ 0.126777  │
│ 36          ┆ 12  ┆ 619       ┆ 0.160882  │
│ 36          ┆ 13  ┆ 633       ┆ 0.195758  │
│ 36          ┆ 14  ┆ 688       ┆ 0.233664  │
│ 36          ┆ 15  ┆ 678       ┆ 0.271019  │
│ 36          ┆ 16  ┆ 721       ┆ 0.310744  │
│ 36          ┆ 17  ┆ 700       ┆ 0.349311  │
│ 36          ┆ 18  ┆ 708       ┆ 0.38832   │
│ 36          ┆ 19  ┆ 671       ┆ 0.425289  │
│ 36          ┆ 20  ┆ 650       ┆ 0.461102  │
│ 36          ┆ 21  ┆ 627       ┆ 0.495647  │
│ 36          ┆ 22  ┆ 670       ┆ 0.532562  │
│ 36          ┆ 23  ┆ 701       ┆ 0.571185  │
│ 36          ┆ 24  ┆ 585       ┆ 0.603416  │
│ 36          ┆ 25  ┆ 622       ┆ 0.637686  │
│ 36          ┆ 26  ┆ 618       ┆ 0.671736  │
│ 36          ┆ 27  ┆ 603       ┆ 0.704959  │
│ 36          ┆ 28  ┆ 558       ┆ 0.735702  │
│ 36          ┆ 29  ┆ 562       ┆ 0.766667  │
│ 36          ┆ 30  ┆ 524       ┆ 0.795537  │
│ 36          ┆ 31  ┆ 441       ┆ 0.819835  │
│ 36          ┆ 32  ┆ 473       ┆ 0.845895  │
│ 36          ┆ 33  ┆ 420       ┆ 0.869036  │
│ 36          ┆ 34  ┆ 418       ┆ 0.892066  │
│ 36          ┆ 35  ┆ 412       ┆ 0.914766  │
│ 36          ┆ 36  ┆ 361       ┆ 0.934656  │
│ 36          ┆ 37  ┆ 324       ┆ 0.952507  │
│ 36          ┆ 38  ┆ 295       ┆ 0.96876   │
│ 36          ┆ 39  ┆ 250       ┆ 0.982534  │
│ 36          ┆ 40  ┆ 182       ┆ 0.992562  │
│ 36          ┆ 41  ┆ 63        ┆ 0.996033  │
│ 36          ┆ 42  ┆ 38        ┆ 0.998127  │
│ 36          ┆ 43  ┆ 26        ┆ 0.999559  │
│ 36          ┆ 44  ┆ 2         ┆ 0.999669  │
│ 36          ┆ 45  ┆ 3         ┆ 0.999835  │
└─────────────┴─────┴───────────┴───────────┘

## 4. Does censoring also inflate measured AUC?

Censoring inflates the default rate unconditionally. It inflates *discrimination* only
if who-prepays correlates with risk — in that case the matured subset is a risk-widened
sample and its AUC is optimistic too.

**Decision rule:** if early payers average more than ~10 FICO points above on-schedule
payers, the reported OOT AUC of 0.721 is optimistic, not just the OOT default rate.

In [9]:
prepay = prepayment_risk_link(raw, vintages=[2012, 2013])
prepay

shape: (4, 5)
┌─────────────┬─────────────┬───────┬────────────┬───────────┐
│ term_months ┆ early_payer ┆ n     ┆ mean_fico  ┆ mean_dti  │
│ ---         ┆ ---         ┆ ---   ┆ ---        ┆ ---       │
│ i32         ┆ bool        ┆ u32   ┆ f64        ┆ f64       │
╞═════════════╪═════════════╪═══════╪════════════╪═══════════╡
│ 36          ┆ false       ┆ 63849 ┆ 697.945074 ┆ 16.921249 │
│ 36          ┆ true        ┆ 61762 ┆ 698.229332 ┆ 16.092545 │
│ 60          ┆ false       ┆ 9146  ┆ 699.214411 ┆ 18.771905 │
│ 60          ┆ true        ┆ 23746 ┆ 698.683778 ┆ 17.558057 │
└─────────────┴─────────────┴───────┴────────────┴───────────┘

In [10]:
fico_gap = (
    prepay.pivot(on="early_payer", index="term_months", values="mean_fico")
    .with_columns((pl.col("true") - pl.col("false")).alias("fico_gap_early_minus_scheduled"))
)
fico_gap

shape: (2, 4)
┌─────────────┬────────────┬────────────┬────────────────────────────────┐
│ term_months ┆ false      ┆ true       ┆ fico_gap_early_minus_scheduled │
│ ---         ┆ ---        ┆ ---        ┆ ---                            │
│ i32         ┆ f64        ┆ f64        ┆ f64                            │
╞═════════════╪════════════╪════════════╪════════════════════════════════╡
│ 36          ┆ 697.945074 ┆ 698.229332 ┆ 0.284258                       │
│ 60          ┆ 699.214411 ┆ 698.683778 ┆ -0.530632                      │
└─────────────┴────────────┴────────────┴────────────────────────────────┘

## Summary — parameters this notebook decides

| Parameter | Source | Value |
|---|---|---|
| 2016 OOT usable as-is? | section 1, `bias_gap` | |
| `train_start` (new) | section 2, `first_reliable_year` | |
| Horizon H, term 36 | section 3, `cum_share` >= 0.90 | |
| Horizon H, term 60 | section 3, `cum_share` >= 0.90 | |
| OOT AUC also inflated? | section 4, `fico_gap` | |

Fill this in, then it feeds directly into: rewriting `data/target.py` to a fixed
outcome window, shifting `split.train_end`'s lower bound in `configs/base.yaml`,
and re-running every number in `docs/modeling_findings.md`.

In [11]:
from credit_risk.data.diagnostics import charge_off_proxy_check

proxy = charge_off_proxy_check(raw, vintages=[2012, 2013])
proxy.write_csv("../docs/charge_off_proxy_check.csv")
proxy

shape: (2, 7)
┌──────────────┬───────┬────────────────────┬────────────────────┬──────────┬──────────┬──────────┐
│ has_recovery ┆ n     ┆ med_mob_last_pymnt ┆ med_n_pymt_implied ┆ med_gap  ┆ gap_p25  ┆ gap_p75  │
│ ---          ┆ ---   ┆ ---                ┆ ---                ┆ ---      ┆ ---      ┆ ---      │
│ bool         ┆ u32   ┆ f64                ┆ f64                ┆ f64      ┆ f64      ┆ f64      │
╞══════════════╪═══════╪════════════════════╪════════════════════╪══════════╪══════════╪══════════╡
│ false        ┆ 1946  ┆ 20.0               ┆ 20.0               ┆ 0.0      ┆ 0.0      ┆ 0.949993 │
│ true         ┆ 27572 ┆ 18.0               ┆ 17.971186          ┆ 0.012246 ┆ 0.001482 ┆ 1.0      │
└──────────────┴───────┴────────────────────┴────────────────────┴──────────┴──────────┴──────────┘